name: page_turn
description: Page Turn Widget | Add a page turn effect to widgets in your app.
version: 1.0.1
homepage: https://github.com/fluttercommunity/page_turn
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   uses-material-design: true

